# Generated by Django 4.2.7 on 2025-09-29 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("journals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalreminder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalanalytics",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_analytics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="journalanalytics",
            index=models.Index(
                fields=["user", "date"], name="journals_an_user_id_401f9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalanalytics",
            index=models.Index(
                fields=["week_start"], name="journals_an_week_st_920ba0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalanalytics",
            index=models.Index(
                fields=["month_start"], name="journals_an_month_s_56438c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journalanalytics",
            unique_together={("user", "date")},
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["user", "-created_at"], name="journals_jo_user_id_820538_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["mood_level"], name="journals_jo_mood_le_8090d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["risk_level"], name="journals_jo_risk_le_dfee77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journal",
            index=models.Index(
                fields=["created_at"], name="journals_jo_created_4dee08_idx"
            ),
        ),
    ]
